const money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});let data,view;
const el=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function summary(rows){let receitas=0,despesas=0,cats={},evo={};for(const x of rows){if(x.tipo==='Receita')receitas+=x.valor;else{despesas+=x.valor;cats[x.categoria]=(cats[x.categoria]||0)+x.valor}const m=x.data.slice(0,7);evo[m]=(evo[m]||0)+(x.tipo==='Receita'?x.valor:-x.valor)}return{receitas,despesas,saldo:receitas-despesas,cats,evo}}
// A largura sai pelo CSSOM, não por atributo style: a CSP de produção usa
// style-src 'self' sem 'unsafe-inline', que descarta estilo inline e deixaria
// toda barra do mesmo tamanho.
function bars(alvo,obj){const itens=Object.entries(obj),max=Math.max(1,...itens.map(([,v])=>Math.abs(v))),destino=el(alvo);destino.innerHTML=itens.map(([k,v])=>`<div class="bar"><span>${esc(k)}</span><span class="track"><i></i></span><b>${money(v)}</b></div>`).join('')||'Sem dados neste filtro.';destino.querySelectorAll('.track i').forEach((barra,i)=>{barra.style.width=Math.abs(itens[i][1])/max*100+'%'})}
// O Notion devolve as linhas na ordem da base, não por data: a coluna Data saía
// pulando de 06 para 02 e voltando para 05, o que num painel financeiro lê como
// dado quebrado. Ordena decrescente (ISO compara como texto) sobre a cópia que o
// filter() já devolveu, sem tocar em data.lancamentos.
function render(){let rows=data.lancamentos.filter(x=>(!el('mes').value||x.data.startsWith(el('mes').value))&&(!el('tipo').value||x.tipo===el('tipo').value)&&(!el('categoria').value||x.categoria===el('categoria').value)&&(!el('status').value||x.status===el('status').value)).sort((a,b)=>b.data.localeCompare(a.data));const s=summary(rows);for(const k of ['receitas','despesas','saldo'])el(k).textContent=money(s[k]);el('orcamento').textContent=money(data.orcamentos.reduce((a,x)=>a+x.limite,0));bars('categorias',s.cats);bars('evolucao',s.evo);el('lancamentos').innerHTML=rows.map(x=>`<tr><td>${esc(x.data)}</td><td>${esc(x.nome)}</td><td>${esc(x.tipo)}</td><td>${esc(x.categoria)}</td><td>${esc(x.status)}</td><td>${money(x.valor)}</td></tr>`).join('');}
function apply(d){data=d;el('mes').innerHTML='<option value="">Todos</option>'+[...new Set(d.lancamentos.map(x=>x.data.slice(0,7)))].map(x=>`<option>${esc(x)}</option>`).join('');el('categoria').innerHTML='<option value="">Todas</option>'+[...new Set(d.lancamentos.map(x=>x.categoria))].map(x=>`<option>${esc(x)}</option>`).join('');el('custos').innerHTML=d.custos.map(x=>`<div class="row"><span>${esc(x.nome)}</span><b>${money(x.valor)}</b></div>`).join('');el('orcamentos').innerHTML=d.orcamentos.map(x=>`<div class="row"><span>${esc(x.categoria)}</span><b>${money(x.realizado)} / ${money(x.limite)}</b></div>`).join('');document.querySelectorAll('select').forEach(x=>x.onchange=render);render()}
async function load(){el('sync').textContent='Atualizando…';try{const r=await fetch('/api/dashboard',{cache:'no-store'});if(!r.ok)throw Error();apply(await r.json());el('sync').textContent='Última atualização: '+new Date().toLocaleTimeString('pt-BR')}catch(e){el('sync').textContent=data?'Notion indisponível · mantendo último estado':'Modo offline · snapshot';if(!data)apply(await fetch('data.json').then(r=>r.json()))}}
el('refresh').onclick=load;load();setInterval(load,20000);
